Introduction to Numpy and Panda

In [ ]:
import numpy as np

# Create an array using np.array()
array1 = np.array([
    [10, 12, 14, 16, 18],
    [20, 22, 24, 26, 28],
    [30, 32, 34, 36, 38],
    [40, 42, 44, 46, 48]
])
print(array1)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [ ]:
#1. Display the shape, size, and datatype of the array.
print("Shape of array: ", array1.shape)
print("Size of array: ",array1.size)
print("Datatype of array: ",array1.dtype)

Shape of array:  (4, 5)
Size of array:  20
Datatype of array:  int64


In [ ]:
#2. Find the sum of all elements in the dataset.
print("Sum of all elements in array: ",array1.sum())

Sum of all elements in array:  580


In [ ]:
#1. Create a 1-D NumPy array that contains only even values
array2=array1[array1%2==0]
print(array2)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
#Count the total number of even elements.
even=np.sum(array1%2==0)
print("Count the total number of even elements: ",even)

Count the total number of even elements:  20


In [ ]:
# Extract the third column.
third_column = array1[:, 2]
print(third_column)

[14 24 34 44]


In [ ]:
#2. Extract the second row
second_row = array1[1, :]
print(second_row)

[20 22 24 26 28]


In [ ]:
# Extract a sub-matrix consisting of rows 2–3 and columns 2-5
sub_matrix = array1[1:3, 2:5]
print(sub_matrix)

[[24 26 28]
 [34 36 38]]


In [ ]:
# Replace all values greater than 30 with −1.
array1[array1>30]=-1
print(array1)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [ ]:
#2. Set the fourth row to [1, 2, 3, 4, 5].
array1[3:,]=[1,2,3,4,5]
print(array1)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [ 1  2  3  4  5]]


In [ ]:
#Boolean Indexing (Single-Line Operations)
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
scores = np.array([126, 115, 130, 141, 132])

scores_less_than_130 = scores[scores < 130]
print("Scores less than 130:", scores_less_than_130)

Scores less than 130: [126 115]


In [ ]:
statira_scores = scores[names == "Statira"]
print("Statira's scores:", statira_scores)

Statira's scores: [115 141]


In [ ]:
roxana_mask = (names == "Roxana")
scores[roxana_mask] += 10
print("Scores after adding 10 marks to Roxana's scores:", scores)

Scores after adding 10 marks to Roxana's scores: [146 115 150 141 152]


In [ ]:
row1 = -1 * np.ones((1, 4))
row2 = np.zeros((1, 4))
row3 = 2 * np.ones((1, 4))
result = np.vstack((row1, row2, row3))
print(result)

[[-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 2.  2.  2.  2.]]


In [ ]:
a1=np.arange(12).reshape((3,4))
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
res=a1+100
print(res)

[[102 102 102 102]
 [102 102 102 102]
 [102 102 102 102]]


In [ ]:
res2=2**a1
print(res2)

[[   1    2    4    8]
 [  16   32   64  128]
 [ 256  512 1024 2048]]


In [ ]:
import numpy as np
a = np.arange(10, 50, 2).reshape(4, 5)
print(a)


[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [ ]:
third_column = a[:, 2]
print(third_column)


[14 24 34 44]


In [ ]:
a[3] = [1, 2, 3, 4, 5]
print(a)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [ 1  2  3  4  5]]
